[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simulation_backend"
version = "0.1.0"
requires-python = ">=3.11"
description = "Simulation backend"

dependencies = [
    "gmsh",
    "matplotlib",    
]

[project.optional-dependencies]

tests = [
    "pytest",
    "pytest-cov",
    "watchdog",
    "ruff",
    "coverage",
]

docs = [
    "sphinx",
    "autodocsumm>=0.2.14",
    "pydata-sphinx-theme",
    "sphinx_mdinclude",
    "sphinx-design",
    "sphinx-favicon",
    "sphinx-reredirects",
    "myst-parser",
    "sphinx-copybutton",
    "sphinx-gallery",
]

dev = ["simulation_backend[tests,docs]"]

[tool.setuptools]
# Explicitly declare that this distribution does not define top-level packages.
packages = []